# Parcial 1 - Programación 3
# Integrantes: Natalia García Hidalgo, Diego Rincón Álvarez

defmodule Datos do
  def recolectores do
    [
      %{codigo: "R01", nombre: "Luz Marina Ospina", alimentacion: true},
      %{codigo: "R02", nombre: "Jhon Fredy Castaño", alimentacion: false},
      %{codigo: "R03", nombre: "Dora Cardona", alimentacion: true},
      %{codigo: "R04", nombre: "Wilson Arango", alimentacion: false},
      %{codigo: "R05", nombre: "Gloria Patricia Rendón", alimentacion: true},
      %{codigo: "R06", nombre: "Carlos Andrés Giraldo", alimentacion: false},
      %{codigo: "R07", nombre: "María Eugenia Salazar", alimentacion: true},
      %{codigo: "R08", nombre: "Duván Esteban Marín", alimentacion: false},
      %{codigo: "R09", nombre: "Yesenia Londoño", alimentacion: true},
      %{codigo: "R10", nombre: "Hernán Darío Quintero", alimentacion: false},
      %{codigo: "R11", nombre: "Rosalba Montoya", alimentacion: true},
      %{codigo: "R12", nombre: "Óscar Iván Beltrán", alimentacion: false}
    ]
  end

  def lotes do
    [
      %{id: "L1", nombre: "El Mirador", hectareas: 2.5},
      %{id: "L2", nombre: "La Cañada", hectareas: 1.5},
      %{id: "L3", nombre: "Buenavista", hectareas: 3.0},
      %{id: "L4", nombre: "El Porvenir", hectareas: 2.0}
    ]
  end

  def pesajes do
    [
      %{recolector: "R01", lote: "L4", dia: 2, kilos: 55, verdes: 10},
      %{recolector: "R04", lote: "L4", dia: 3, kilos: 105, verdes: 2.5},
      %{recolector: "R11", lote: "L1", dia: 4, kilos: 70, verdes: 4},
      %{recolector: "R01", lote: "L4", dia: 4, kilos: 60.5, verdes: 0.5},
      %{recolector: "R08", lote: "L2", dia: 4, kilos: 80, verdes: 12},
      %{recolector: "R04", lote: "L3", dia: 6, kilos: 50, verdes: 15},
      %{recolector: "R02", lote: "L1", dia: 1, kilos: 80, verdes: 2},
      %{recolector: "R01", lote: "L4", dia: 1, kilos: 120, verdes: 5},
      %{recolector: "R02", lote: "L2", dia: 3, kilos: 60, verdes: 8},
      %{recolector: "R08", lote: "L3", dia: 3, kilos: 120, verdes: 2},
      %{recolector: "R05", lote: "L3", dia: 5, kilos: 30, verdes: 0.5},
      %{recolector: "R08", lote: "L2", dia: 1, kilos: 55, verdes: 11},
      %{recolector: "R02", lote: "L3", dia: 4, kilos: 60, verdes: 1.5},
      %{recolector: "R07", lote: "L3", dia: 2, kilos: 35.5, verdes: 9},
      %{recolector: "R08", lote: "L3", dia: 5, kilos: 35, verdes: 6},
      %{recolector: "R05", lote: "L4", dia: 2, kilos: 90.5, verdes: 8},
      %{recolector: "R02", lote: "L3", dia: 3, kilos: 35.5, verdes: 10},
      %{recolector: "R07", lote: "L2", dia: 3, kilos: 55, verdes: 15},
      %{recolector: "R01", lote: "L4", dia: 2, kilos: 40, verdes: 5},
      %{recolector: "R07", lote: "L4", dia: 3, kilos: 40.5, verdes: 2.5},
      %{recolector: "R06", lote: "L1", dia: 6, kilos: 45, verdes: 2.5},
      %{recolector: "R05", lote: "L4", dia: 2, kilos: 75, verdes: 4.5},
      %{recolector: "R04", lote: "L3", dia: 4, kilos: 85.5, verdes: 4},
      %{recolector: "R04", lote: "L1", dia: 1, kilos: 70, verdes: 12},
      %{recolector: "R08", lote: "L1", dia: 1, kilos: 110, verdes: 3},
      %{recolector: "R07", lote: "L1", dia: 6, kilos: 20.5, verdes: 11},
      %{recolector: "R04", lote: "L1", dia: 4, kilos: 45, verdes: 5},
      %{recolector: "R07", lote: "L2", dia: 4, kilos: 50, verdes: 4},
      %{recolector: "R05", lote: "L4", dia: 1, kilos: 110, verdes: 15},
      %{recolector: "R06", lote: "L2", dia: 4, kilos: 90, verdes: 15},
      %{recolector: "R03", lote: "L4", dia: 3, kilos: 45, verdes: 2.5},
      %{recolector: "R03", lote: "L4", dia: 5, kilos: 20.5, verdes: 3.5},
      %{recolector: "R08", lote: "L4", dia: 2, kilos: 90, verdes: 4},
      %{recolector: "R07", lote: "L1", dia: 1, kilos: 80, verdes: 9},
      %{recolector: "R06", lote: "L4", dia: 3, kilos: 70, verdes: 1},
      %{recolector: "R03", lote: "L3", dia: 1, kilos: 35, verdes: 6},
      %{recolector: "R03", lote: "L3", dia: 3, kilos: 80, verdes: 1.5},
      %{recolector: "R05", lote: "L4", dia: 4, kilos: 60, verdes: 6},
      %{recolector: "R04", lote: "L3", dia: 1, kilos: 105, verdes: 7},
      %{recolector: "R10", lote: "L1", dia: 1, kilos: 200, verdes: 1},
      %{recolector: "R02", lote: "L1", dia: 5, kilos: 20, verdes: 4},
      %{recolector: "R02", lote: "L4", dia: 4, kilos: 105.5, verdes: 11},
      %{recolector: "R07", lote: "L1", dia: 2, kilos: 105, verdes: 1},
      %{recolector: "R06", lote: "L4", dia: 5, kilos: 30, verdes: 9},
      %{recolector: "R01", lote: "L2", dia: 1, kilos: 50, verdes: 9},
      %{recolector: "R03", lote: "L3", dia: 4, kilos: 50, verdes: 3.5},
      %{recolector: "R03", lote: "L3", dia: 4, kilos: 75, verdes: 1},
      %{recolector: "R01", lote: "L4", dia: 3, kilos: 45.5, verdes: 6},
      %{recolector: "R10", lote: "L4", dia: 3, kilos: 20, verdes: 15},
      %{recolector: "R09", lote: "L3", dia: 2, kilos: 90.5, verdes: 5},
      %{recolector: "R09", lote: "L4", dia: 1, kilos: 75, verdes: 6},
      %{recolector: "R03", lote: "L1", dia: 1, kilos: 85, verdes: 11},
      %{recolector: "R02", lote: "L2", dia: 2, kilos: 120, verdes: 8},
      %{recolector: "R09", lote: "L2", dia: 3, kilos: 95.5, verdes: 1.5},
      %{recolector: "R06", lote: "L4", dia: 1, kilos: 70.5, verdes: 1},
      %{recolector: "R09", lote: "L1", dia: 1, kilos: 100, verdes: 10},
      %{recolector: "R04", lote: "L1", dia: 5, kilos: 30.5, verdes: 12},
      %{recolector: "R09", lote: "L4", dia: 2, kilos: 105, verdes: 10},
      %{recolector: "R07", lote: "L4", dia: 5, kilos: 45, verdes: 6},
      %{recolector: "R08", lote: "L2", dia: 2, kilos: 70.5, verdes: 0.5},
      %{recolector: "R06", lote: "L4", dia: 1, kilos: 120, verdes: 8},
      %{recolector: "R09", lote: "L2", dia: 4, kilos: 50, verdes: 1.5},
      %{recolector: "R10", lote: "L2", dia: 2, kilos: 20, verdes: 12},
      %{recolector: "R03", lote: "L3", dia: 2, kilos: 105, verdes: 2.5},
      %{recolector: "R07", lote: "L4", dia: 1, kilos: 120, verdes: 0},
      %{recolector: "R06", lote: "L2", dia: 2, kilos: 105, verdes: 1},
      %{recolector: "R01", lote: "L2", dia: 3, kilos: 120, verdes: 2},
      %{recolector: "R08", lote: "L3", dia: 6, kilos: 40, verdes: 4.5},
      %{recolector: "R06", lote: "L4", dia: 2, kilos: 95, verdes: 4.5},
      %{recolector: "R05", lote: "L1", dia: 6, kilos: 40, verdes: 3},
      %{recolector: "R02", lote: "L4", dia: 2, kilos: 50, verdes: 11},
      %{recolector: "R01", lote: "L3", dia: 5, kilos: 45, verdes: 1.5},
      %{recolector: "R04", lote: "L4", dia: 2, kilos: 110, verdes: 4},
      %{recolector: "R08", lote: "L1", dia: 3, kilos: 40, verdes: 3},
      %{recolector: "R09", lote: "L4", dia: 3, kilos: 35.5, verdes: 11},
      %{recolector: "R09", lote: "L3", dia: 4, kilos: 60, verdes: 10},
      %{recolector: "R05", lote: "L2", dia: 3, kilos: 120.5, verdes: 5},
      %{recolector: "R05", lote: "L4", dia: 1, kilos: 50, verdes: 10},
      %{recolector: "R09", lote: "L1", dia: 5, kilos: 45, verdes: 0},
      %{recolector: "R01", lote: "L4", dia: 4, kilos: 80, verdes: 5},
      %{recolector: "R11", lote: "L3", dia: 2, kilos: 95, verdes: 2.5},
      %{recolector: "R15", lote: "L1", dia: 1, kilos: 80, verdes: 3},
      %{recolector: "R20", lote: "L3", dia: 4, kilos: 60, verdes: 2},
      %{recolector: "R03", lote: "L9", dia: 2, kilos: 50, verdes: 2},
      %{recolector: "R05", lote: "L0", dia: 5, kilos: 75, verdes: 4},
      %{recolector: "R04", lote: "L3", dia: 7, kilos: 300, verdes: 3},
      %{recolector: "R06", lote: "L2", dia: 0, kilos: 60, verdes: 3.5},
      %{recolector: "R02", lote: "L1", dia: 3.5, kilos: 45, verdes: 2},
      %{recolector: "R02", lote: "L2", dia: 3, kilos: 0, verdes: 4},
      %{recolector: "R01", lote: "L3", dia: 3, kilos: 300, verdes: 2},
      %{recolector: "R07", lote: "L4", dia: 5, kilos: -20, verdes: 1},
      %{recolector: "R01", lote: "L2", dia: 3, kilos: 40, verdes: 130},
      %{recolector: "R08", lote: "L1", dia: 4, kilos: 55, verdes: -5},
      %{recolector: "R12", lote: "L2", dia: 2, kilos: 60, verdes: 101},
      %{recolector: "R12", lote: "L3", dia: 5, kilos: 251, verdes: 2}
    ]
  end
end
